baseURL: "https://mngaafar.com"
languageCode: "en-us"
title: "Mohamed Nasser Gaafar"
theme: hugo-profile

Paginate: 3
googleAnalytics: G-5GL6K1NVFM

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Mohamed Nasser Gaafar"
  description: This is my personal blog and portfolio
  # staticPath: ""  # The path to serve the static files from
  # favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: false
    defaultTheme: "dark" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Mohamed."
    subtitle: "I build things."
    content: "A passionate biomedical software engineer. I find joy in building solutions that solve problems that matter. 
"
    image: /images/hero.svg
    button:
      enable: true
      name: "Resume"
      #TODO: update resume
      url: "https://drive.google.com/uc?export=download&id=13I5iBoQa2GHrGxzJKrDxsTFoNUi-nssQ"
      download: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/mo-gaafar
        - icon: fab fa-twitter
          url: https://twitter.com/moe_gaafar
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/mn-gaafar

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. 

      I am currently working on a project that will be used to help people find the best way to get around the city.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Hardware Design Engineer"
        company: "Formula Student Cairo University"
        companyUrl: "https://example.com"
        date: "Sept 2022 - Present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "Working as a core team member, designing, testing and implementing the racing car's low voltage system"
        
      - job: "Backend Developer"
        company: "Shell Eco Racing Team Cairo University"
        companyUrl: "https://example.com"
        date: "Sept 2022 - Present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "Working on the backend of the team's website, Familiar with tokens and authentication, REST API, Django"
        
      - job: "Clinical Engineering Intern"
        company: "Al Assema Hospitals"
        companyUrl: "https://example.com"
        date: "Aug 2022 - Sept 2022"
        featuredLink:
          enable: true
          url: "https://example.com"
        info:
          enable: true
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

      - job: "Intern Software Developer"
        company: "Clear Pictures"
        companyUrl: "https://example.com"
        date: "Jul 2022 - Aug 2022"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "I am currently building my knowledge in the healthcare and hospitals field and learning more about the structure and work culture."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    # index: true
    items:
      - title: "Bachelor of Science in Systems and Biomedical Engineering"
        school:
          name: "Cairo University, Giza, Egypt"
          url: "https://eng.cu.edu.eg"
        date: "2019 - 2024"
        GPA: "3.39 out of 4.0"
        content: |-
          Projects I have worked on include
          - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
          - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.

          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Al Bashaer International Schools (IGCSE)"
          url: "https://example.org"
        GPA: "3.95 out of 4.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  #TODO: finish this section
  projects:
    enable: true
    title: "WORK IN PROGRESS"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-envelope
            url: mailto:mohamed_gaafar@ieee.org?subject=Website%20Email&body=Hello%20welcome%20to%20my%20website%2C%20feel%20free%20to%20ask%20me%20anything%20here%20
          - icon: fab fa-github
            url: https://github.com/mo-gaafar
          - icon: fab fa-twitter
            url: https://twitter.com/moe_gaafar

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://www.google.com
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: www.google.com

  #Contact
  contact:
    enable: true
    #title: "Custom name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: mohamed_gaafar@ieee.org
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/mo-gaafar
      linkedin: https://linkedin.com/in/mn-gaafar
      twitter: https://twitter.com/moe_gaafar
      instagram: https://instagram.com/mo.nasserr
