title = "M. N. Gaafar"
baseURL = "https://www.mngaafar.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = true

[params]
lastName = "N. Gaafar"
showOpenSource = false
showPublications = false
showExperience = true
showResume = true
showEducation = true
phone = "+201155277008"
profileImage = "img/mngaafar-avatar-thumb.png"
favicon = "/favicon.ico"
address = "Cairo, EG"
showProjects = false
showSocializations = true
firstName = "Mohamed"
email = "mohamed_gaafar@ieee.org"
showQr = true
showBlog = true
showSkills = false

[[params.handles]]
link = "https://github.com/mo-gaafar/"
name = "GitHub"
icon = "fa-github-alt"

[[params.handles]]
link = "https://www.linkedin.com/in/mn-gaafar/"
name = "LinkedIn"

[[params.handles]]
link = "https://twitter.com/jaafar_dev/"
name = "Twitter"

[params.google]

[params.google.analytics]
trackerID = "G-5GL6K1NVFM"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"