title = "M. N. Gaafar"
baseURL = "https://www.mngaafar.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = true

[params]
address = "Cairo, EG"
email = "mohamed_gaafar@ieee.org"
favicon = "/favicon.ico"
firstName = "Mohamed"
lastName = "N. Gaafar"
phone = "+201155277008"
profileImage = "img/mngaafar-avatar-thumb.png"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = false
showSocializations = true
showQr = true
showSkills = false

[params.google]

[params.google.analytics]
trackerID = "G-5GL6K1NVFM"

[[params.handles]]
link = "https://www.linkedin.com/in/mn-gaafar/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/mo-gaafar/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"